### ISSUE TITLE
Create a Token...

### ISSUE THREAD

**Issue by sharkbit** [IntuitDeveloper/PHPPaymentSample#1]
This is great but, where is the code to generate the transaction accessToken...
the default sting you have for $accessToken is over 800 chars

**Comment by sharkbit** [comment]
Searching for most of the day and it looks like the $accessToken is made up of a lot of things.

`$accessToken = 'OAuth oauth_consumer_key=\"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\",'.
			   'oauth_token=\"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\",'.
			   'oauth_signature_method=\"HMAC-SHA1\",'.
			   'oauth_timestamp=\"1495132036\",'.
			   'oauth_nonce=\"XXXXXX\",'.
			   'oauth_version=\"1.0\",'.
			   'oauth_signature=\"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\"';`

So How is this generated?  I was able to use your code and get a Credit Card Token but cant get passed this.

**Comment by sharkbit** [comment]
Even in your [Quickbooks Payments API Explorer ](https://developer.intuit.com/v2/apiexplorer?apiname=Payments#?id=charges) the Charge option has a different 'Authentication header' that it magically puts together for you.   Why is the documentation of the Auth header so hard to find.  and what Auth header should I even try to use.

  `singularityheader: appId=55*ctrlguid=1516350528*acctguid=87bcfab1-ad5a-4af1-95e0-7eed4f8a1800*ts=1523706383163*btid=7742*guid=92c37f32-b160-4e57-8cd0-675547f7d1f8*exitguid=6*unresolvedexitid=7928*cidfrom=390*etypeorder=HTTP*esubtype=HTTP*cidto={[UNRESOLVED][7928]}
`  

Please Break it down.

**Comment by sharkbit** [comment]
Why dosn't this work what am i missing?
`<?php
require ("./CurlClient.php");
use QuickBooksOnline\API\Core\OAuth\OAuth1\OAuth1;

$token=unserialize($confParams->token);  //From github PHPOAuthSample
$myOauth = new OAuth1($confParams->consumerKey,$confParams->consumerSecret,$token['oauth_token'],$token['oauth_token_secret']);

//Change your Access Token Here
//$accessToken = "Bearer " . "JUNK-JUNK-JUNK-JUNK";
//  how did you generate an access token with out the request?

//Add your request ID here
$requestId = "SomeThingUique";


$baseURL = "https://sandbox.api.intuit.com/quickbooks/v4/payments/charges";
$client = new CurlClient();

$body = [
  "amount" => "10.55",
  "card" => [
    "expYear" => "2020",
    "expMonth" => "02",
    "address" => [
      "region" => "CA",
      "postalCode" => "94086",
      "streetAddress" => "1130 Kifer Rd",
      "country" => "US",
      "city" => "Sunnyvale"
    ],
    "name" => "emulate=0",
    "cvc" => "123",
    "number" => "4111111111111111"
  ],
  "currency" => "USD",
  "context" => [
        "mobile" => "false",
        "isEcommerce" => "true"
  ]
];

$myOauth->sign($baseURL, $body, "POST");
$accessToken = $myOauth->getOAuthHeader($baseURL, $body, "POST");
$accessToken = substr($accessToken, 6);
// this still dosnt work

$http_header = array(
      'Accept' => 'application/json',
      'Request-Id' => $requestId,
      'Authorization' => $accessToken,
      'Content-Type' => 'application/json;charset=UTF-8'
);

$intuitResponse = $client->makeAPICall($baseURL, "POST", $http_header, json_encode($body), null, false);

var_dump($intuitResponse );
?>`

**Comment by hlu2** [comment]
The line you have:
$accessToken = $myOauth->getOAuthHeader($baseURL, $body, "POST");
is not correct.

For OAuth 1, if the body is Application/Json, DO NOT include it in the signature. Only include it if it is application/x-www-form-urlencoded. 

In your case, just pass an empty array and it should work:
$accessToken = $myOauth->getOAuthHeader($baseURL, array(), "POST");
