### ISSUE TITLE
Is this actually finished?

### ISSUE THREAD

**Issue by jhitesma** [IntuitDeveloper/PHPPaymentSample#2]
This appears only partly complete.  Yes, this code is "complete" enough that it can perform a rudimentary charge request - but there's nothing here for actually handling the response at any level and the code comments seem to be incomplete or in error in various places.

in CurlClient.php IntuitResponse is defined as "The parsed response from curl client to Intuit customized response"

But following the code it's just the raw output from curl_exec() with no parsing at all.  

There's a method "getHeaders" which is defined as (sic) "Get headers for the QuciKbooks Online Response"

But it's not actually used for parsing the response it's used to set the headers in the request not the response.

**Comment by millertn** [comment]
Bumping for an answer?

**Comment by hlu2** [comment]
@jhitesma @millertn  We are going to have a PHP Payments SDK release soon (in a few weeks) with complete function. The Payments SDK will replace this github.

**Comment by millertn** [comment]
So, I have a deadline of May 10th to get something working for this, can i rig this and one of your php OAuth2 examples together to get something that works?

**Comment by yepwebdev** [comment]
Agreed, it's very difficult to extract any meaningful data from the raw output.
In the `prepareRequest()` function, I changed `CURLOPT_HEADER = 0` to exclude headers from the output.

https://github.com/IntuitDeveloper/PHPPaymentSample/blob/master/CurlClient.php#L75

It's now mid-June.
Is the PHP Payments SDK available yet?

**Comment by hlu2** [comment]
New Payments SDK: https://github.com/intuit/PHP-Payments-SDK
